from __future__ import annotations

import numpy as np
from attrs import define, field, validators

from t4_devkit.typing import Roi

from ..name import SchemaName
from .base import SchemaBase
from .object_ann import RLEMask
from .registry import SCHEMAS

__all__ = ["SurfaceAnn"]


@define(slots=False)
@SCHEMAS.register(SchemaName.SURFACE_ANN)
class SurfaceAnn(SchemaBase):
    """A dataclass to represent schema table of `surface_ann.json`.

    Attributes:
        token (str): Unique record identifier.
        sample_data_token (str): Foreign key pointing to the sample data, which must be a keyframe image.
        category_token (str): Foreign key pointing to the surface category.
        mask (RLEMask): Segmentation mask using the COCO format compressed by RLE.
        automatic_annotation (bool, optional): Indicates if the annotation is fully generated by an ML model.
            If any part is manually modified or annotated by human this value is False.

    Shortcuts:
    ---------
        category_name (str): Category name. This should be set after instantiated.
    """

    sample_data_token: str = field(validator=validators.instance_of(str))
    category_token: str = field(validator=validators.instance_of(str))
    mask: RLEMask | None = field(
        default=None,
        converter=lambda x: RLEMask(**x) if isinstance(x, dict) else x,
        validator=validators.optional(validators.instance_of(RLEMask)),
    )
    automatic_annotation: bool = field(default=False, validator=validators.instance_of(bool))

    # shortcuts
    category_name: str = field(init=False, factory=str)

    @property
    def bbox(self) -> Roi | None:
        """Return a bounding box corners calculated from polygon vertices.

        Returns:
            Roi instance given as [xmin, ymin, xmax, ymax].
        """
        if self.mask is None:
            return None

        mask = self.mask.decode()
        indices = np.where(mask == 1)
        xmin, ymin = np.min(indices, axis=1)
        xmax, ymax = np.max(indices, axis=1)
        return Roi(xmin, ymin, xmax, ymax)
