name: deploy-document

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deplot-document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          cache: "poetry"
          python-version: "3.10"
      - run: poetry install
      - run: poetry run mkdocs gh-deploy --force
