name: deploy-document

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Define a cache dependency glob
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --extra dev

      - name: Create the document
        run: uv run mkdocs gh-deploy --force
